import { ico } from "./icons";
import { Store } from "./store";
import { IDB } from "./db";
import { Router } from "./router";
import { EdgeClient, STATIC_MODELS, PROVIDERS } from "./api";
import type { ModelInfo } from "./api";
import { ChatEngine, DEFAULT_SETTINGS, uid } from "./chat";
import type { AppState, ChatDoc, Settings } from "./chat";
import { localChat } from "./engine";
import { toast, confirmDialog, promptDialog, switchEl, rangeEl } from "./ui";
import { CallManager } from "./call";
import type { CallLine } from "./call";
import { renderMarkdown, escapeHtml } from "./render";
import type { Artifact } from "./render";
import { t, setLang, getLang, applyI18n } from "./i18n";
import type { Lang } from "./i18n";



const ABOUT_MD = `# About shai

**shai** — *the quiet ai*. The name is a whisper: **sh** + **ai**. A studio for working with AI that stays out of the way — no accounts to register, no noise, no lock-in. You, the model, and the work.

## What it is

- A three-column AI studio: conversation history, chat with token-level streaming, and an artifacts panel with live HTML previews.
- **11 model providers** (Gemini, DeepSeek incl. R1, Groq, OpenRouter, Mistral, OpenAI, Anthropic, xAI, Cerebras, SambaNova, local Ollama) plus a built-in offline engine that works with zero keys.
- Web search, deep thinking (chain of thought), images, voice dictation, and **Telegram-style voice & video calls** with barge-in and a live canvas avatar.
- A decentralized layer in active development: DID identities, a serverless mesh of nodes, and AI-to-AI introductions.

## How it is built

The interface is pure **HTML5, CSS3 and Vanilla JavaScript** (ES Modules) — no UI frameworks, every component hand-rolled: state manager on Proxy, hash router, IndexedDB wrapper, SSE parser, 50+ custom SVG icons. The optional backend is **TypeScript on Cloudflare Workers**: it proxies model APIs, aggregates model catalogs into Edge KV, and keeps provider keys server-side. Without a worker, the app runs in direct mode (your keys, your browser) or fully offline.

---

# License

shai is free and open-source software, released under the **MIT License**:

> **MIT License** — Copyright © 2026 shai Contributors
>
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
>
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
>
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

---

# Policies

## Privacy

- **Everything stays on your device.** Conversations, settings, images and the model cache are stored in your browser's IndexedDB. There are no accounts, no cookies, no analytics, no telemetry — the app has no way to phone home.
- **API keys are yours.** In direct mode they never leave your browser. In Edge mode they live only in the worker's secret environment — the worker itself is the only server that sees them, and it can be self-hosted.
- **Identity (DID), when you create one,** is a key pair generated locally with WebCrypto. The private key never leaves the device; ownership of the key *is* the authentication.

## Network & calls

- Node-to-node links use **WebRTC peer-to-peer** channels; signaling is done by exchanging invitation codes you transport yourself. Public STUN servers only help with NAT traversal and never touch your traffic.
- Every network packet is **signed with a DID key**, so peers are verified cryptographically — not by trusting a server.
- Voice calls run through the Web Speech API: synthesis is on-device; recognition, in Chromium browsers, is processed by the browser vendor's speech service.

## Web search

- Lookups are sent to the public Wikipedia API to fetch sources. No identifiers, cookies or account data are attached.

## AI output

- Responses are generated by the model provider **you** select; your prompt is sent only to that provider (or to your own worker/Ollama).
- Models can be wrong. Verify anything important before relying on it.
`;

export async function createStudio(root: HTMLElement): Promise<() => void> {
  const db = new IDB("ai-studio-db", ["chats", "settings", "models", "misc"]);
  const unsubs: (() => void)[] = [];

  const savedChats = (await db.get<ChatDoc[]>("chats", "all")) ?? [];
  const savedSettings = (await db.get<Settings>("settings", "app")) ?? null;
  const savedModel = (await db.get<string>("misc", "modelId")) ?? "shai-local";
  const savedModels = (await db.get<{ ts: number; models: ModelInfo[] }>("models", "list")) ?? null;

  const settings: Settings = { ...DEFAULT_SETTINGS, ...(savedSettings ?? {}) };
  setLang(settings.lang);
  let chats = savedChats;
  if (!chats.length) chats = [makeChat()];

  const cachedModels = (savedModels?.models ?? []).filter((m) => m.provider !== "local");
  const mergedModels = (() => {
    const seen = new Set<string>();
    return [...STATIC_MODELS.filter((m) => m.provider === "local"), ...cachedModels, ...STATIC_MODELS.filter((m) => m.provider !== "local")]
      .filter((m) => (seen.has(m.id) ? false : (seen.add(m.id), true)));
  })();

  const store = new Store<AppState>({
    ready: true,
    chats,
    activeId: chats[0].id,
    settings,
    models: mergedModels,
    modelId: savedModel,
    webSearch: false,
    deepThink: false,
    artOpen: false,
    sidebarOpen: false,
    sideCollapsed: false,
    view: "chat",
  });
  if (!store.state.models.some((m) => m.id === store.state.modelId)) store.state.modelId = "shai-local";

  const client = new EdgeClient(() => store.state.settings.edgeUrl);
  const persist = () => void db.set("chats", "all", store.state.chats);
  const s = () => store.state.settings;
  const set = (patch: Partial<Settings>) => store.setDeep("settings", (prev) => ({ ...prev, ...patch }));

  root.innerHTML = `
    <div class="app-shell">
      <div class="sidebar-scrim"></div>
      <header class="app-header"></header>
      <div class="app-body">
        <aside class="sidebar">
          <div class="side-top">
            <button class="btn btn-primary btn-new">${ico("plus")} <span data-i18n="New chat">New chat</span></button>
            <div class="side-search">${ico("search")}<input data-i18n-ph="Search chats…" placeholder="Search chats…" /></div>
          </div>
          <nav class="chat-list" aria-label="Conversation history"></nav>
          <div class="side-nav">
            <a class="nav-item" href="#/about" data-nav="about">${ico("doc")}<span data-i18n="About & Legal">About &amp; Legal</span></a>
          </div>
          <div class="side-bottom">
            <a class="nav-item side-settings" href="#/settings" data-nav="settings">${ico("gear")}<span data-i18n="Settings">Settings</span></a>
          </div>
        </aside>
        <main class="main-col">
          <div class="view view-chat" data-view="chat"></div>
          <div class="view view-settings" data-view="settings" hidden></div>
          <div class="view view-about" data-view="about" hidden></div>
        </main>
        <aside class="art-panel">
          <div class="art-head">
            <h3>${ico("layers")} <span data-i18n="Artifacts">Artifacts</span> <span class="art-count">0</span></h3>
            <button class="icon-btn art-close" data-i18n-title="Close panel" title="Close panel">${ico("close")}</button>
          </div>
          <div class="art-body"></div>
        </aside>
      </div>
    </div>`;

  const shell = root.querySelector(".app-shell") as HTMLElement;
  const headerEl = root.querySelector(".app-header") as HTMLElement;
  const chatListEl = root.querySelector(".chat-list") as HTMLElement;
  const searchInput = root.querySelector(".side-search input") as HTMLInputElement;
  const artBody = root.querySelector(".art-body") as HTMLElement;
  const artCount = root.querySelector(".art-count") as HTMLElement;
  const viewEls = {
    chat: root.querySelector('[data-view="chat"]') as HTMLElement,
    settings: root.querySelector('[data-view="settings"]') as HTMLElement,
    about: root.querySelector('[data-view="about"]') as HTMLElement,
  };

  function makeChat(): ChatDoc {
    const now = Date.now();
    return { id: uid(), title: t("New conversation"), createdAt: now, updatedAt: now, msgs: [] };
  }

  const router = new Router();
  let callMgr: CallManager | null = null;
  const engine = new ChatEngine(viewEls.chat, {
    store, db, client, router, persist, refreshArtifacts,
    startCall: (kind) => {
      callMgr?.end(false);
      callMgr = new CallManager({
        sttLang: s().sttLang,
        ttsVoice: s().ttsVoice,
        ttsRate: s().ttsRate,
        bargeIn: s().bargeIn,
        getReply: async (text) => {
          const model = store.state.models.find((m) => m.id === store.state.modelId) ?? STATIC_MODELS[0];
          if (model.provider === "local") return localChat(text).text;
          const ac = new AbortController();
          let out = "";
          try {
            for await (const ev of client.chat(model, [
              { role: "system", content: "Reply in English, briefly (max 2 sentences) — this is a voice call." },
              { role: "user", content: text },
            ], { keys: s().keys, signal: ac.signal, deep: false })) {
              if (ev.type === "delta") out += ev.text;
              else if (ev.type === "error") throw new Error(ev.message);
            }
          } catch {
            return localChat(text).text;
          }
          return out || localChat(text).text;
        },
        onEnd: (lines: CallLine[], sec, k) => engine.addCallLog(lines, sec, k),
        onError: (m) => toast(m, "err"),
      });
      void callMgr.start(kind);
    },
    headerEl,
  });

  function groupLabel(ts: number): string {
    const d = new Date(ts);
    const today = new Date();
    const yest = new Date(Date.now() - 864e5);
    const loc = getLang() === "uk" ? "uk-UA" : "en-US";
    if (d.toDateString() === today.toDateString()) return t("Today");
    if (d.toDateString() === yest.toDateString()) return t("Yesterday");
    if (Date.now() - ts < 6 * 864e5) return d.toLocaleDateString(loc, { weekday: "long" });
    return d.toLocaleDateString(loc, { day: "numeric", month: "short" });
  }

  function renderChatList(filter = ""): void {
    const term = filter.trim().toLowerCase();
    const items = store.state.chats
      .filter((c) => !term || c.title.toLowerCase().includes(term) || c.msgs.some((m) => m.content.toLowerCase().includes(term)))
      .sort((a, b) => b.updatedAt - a.updatedAt);
    chatListEl.innerHTML = "";
    if (!items.length) {
      chatListEl.innerHTML = `<div class="list-empty">${ico("search")} ${t("Nothing found")}</div>`;
      return;
    }
    const loc = getLang() === "uk" ? "uk-UA" : "en-US";
    let lastGroup = "";
    for (const c of items) {
      const g = groupLabel(c.updatedAt);
      if (g !== lastGroup) {
        chatListEl.insertAdjacentHTML("beforeend", `<div class="list-group">${g}</div>`);
        lastGroup = g;
      }
      const active = c.id === store.state.activeId && store.state.view === "chat" ? " active" : "";
      chatListEl.insertAdjacentHTML("beforeend", `
        <div class="chat-item${active}" data-id="${c.id}">
          <a class="ci-main" href="#/c/${c.id}">
            <span class="ci-title">${escapeHtml(c.title)}</span>
            <span class="ci-time">${new Date(c.updatedAt).toLocaleTimeString(loc, { hour: "2-digit", minute: "2-digit" })}</span>
          </a>
          <span class="ci-actions">
            <button data-ciact="rename" title="${t("Rename")}">${ico("edit")}</button>
            <button data-ciact="del" title="${t("Delete")}">${ico("trash")}</button>
          </span>
        </div>`);
    }
  }

  let artList: Artifact[] = [];
  let artSel = "";
  let artTab: "code" | "preview" = "code";

  function refreshArtifacts(): void {
    const chat = store.state.chats.find((c) => c.id === store.state.activeId);
    artList = (chat?.msgs ?? []).flatMap((m) => m.arts ?? []);
    if (artSel && !artList.some((a) => a.id === artSel)) artSel = "";
    renderArtifacts();
  }

  function renderArtifacts(): void {
    artCount.textContent = String(artList.length);
    if (!artList.length) {
      artBody.innerHTML = `<div class="art-empty">${ico("layers")}<b>${t("Artifacts")}</b><span>${t("Code blocks from replies appear here")}</span></div>`;
      return;
    }
    const sel = artList.find((a) => a.id === artSel) ?? artList[artList.length - 1];
    artSel = sel.id;
    const isHtml = sel.lang === "html";
    const body = `
      <div class="art-list">${artList.map((a) => `
        <button class="art-item${a.id === artSel ? " active" : ""}" data-art="${a.id}">
          ${ico("code")}
          <span class="ai-main"><b>${escapeHtml(a.title)}</b><small>${new Date(a.ts).toLocaleTimeString(getLang() === "uk" ? "uk-UA" : "en-US", { hour: "2-digit", minute: "2-digit" })}</small></span>
        </button>`).join("")}
      </div>
      <div class="art-view">
        <div class="art-tabs">
          <button class="art-tab${artTab === "code" ? " on" : ""}" data-atab="code">${ico("code")} ${t("Code")}</button>
          ${isHtml ? `<button class="art-tab${artTab === "preview" ? " on" : ""}" data-atab="preview">${ico("eye")} ${t("Preview")}</button>` : ""}
          <span class="art-spacer"></span>
          <button class="icon-btn" data-aact="copy" title="${t("Copy")}">${ico("copy")}</button>
          <button class="icon-btn" data-aact="dl" title="${t("Download")}">${ico("download")}</button>
        </div>
        <div class="art-content"></div>
      </div>`;
    artBody.innerHTML = body;
    const content = artBody.querySelector(".art-content")!;
    if (artTab === "preview" && isHtml) {
      const fr = document.createElement("iframe");
      fr.className = "art-frame";
      fr.sandbox.add("allow-scripts");
      fr.srcdoc = sel.code;
      content.appendChild(fr);
    } else {
      content.innerHTML = `<div class="codeblock"><div class="cb-head"><span class="cb-lang">${escapeHtml(sel.lang)}</span></div><div class="cb-body"><pre><code>${escapeHtml(sel.code)}</code></pre></div></div>`;
    }
    artBody.querySelectorAll("[data-art]").forEach((b) =>
      b.addEventListener("click", () => { artSel = b.getAttribute("data-art")!; artTab = "code"; renderArtifacts(); })
    );
    artBody.querySelectorAll("[data-atab]").forEach((b) =>
      b.addEventListener("click", () => { artTab = b.getAttribute("data-atab") as "code" | "preview"; renderArtifacts(); })
    );
    artBody.querySelector('[data-aact="copy"]')!.addEventListener("click", async () => {
      await navigator.clipboard.writeText(sel.code).catch(() => {});
      toast(t("Copied to clipboard"), "ok");
    });
    artBody.querySelector('[data-aact="dl"]')!.addEventListener("click", () => {
      const ext = { html: "html", js: "js", javascript: "js", ts: "ts", typescript: "ts", python: "py", py: "py", css: "css", json: "json", bash: "sh", sql: "sql" }[sel.lang] ?? "txt";
      const a = document.createElement("a");
      a.href = URL.createObjectURL(new Blob([sel.code], { type: "text/plain" }));
      a.download = `artifact-${sel.id.slice(0, 6)}.${ext}`;
      a.click();
      URL.revokeObjectURL(a.href);
    });
  }

  function showView(name: "chat" | "settings" | "about"): void {
    store.state.view = name;
    store.state.sidebarOpen = false;
    headerEl.classList.toggle("chat-mode", name === "chat");
    for (const [k, v] of Object.entries(viewEls)) v.hidden = k !== name;
    root.querySelectorAll(".nav-item").forEach((n) => n.classList.toggle("active", n.getAttribute("data-nav") === name));
    if (name === "settings") renderSettings();
    if (name === "about") renderAbout();
  }

  function renderAbout(): void {
    viewEls.about.innerHTML = `<div class="doc-view"><div class="md-content">${renderMarkdown(ABOUT_MD)}</div></div>`;
  }

  function renderSettings(): void {
    const host = viewEls.settings;
    host.innerHTML = `
      <div class="set-view">
        <header class="set-head"><h2>${ico("gear")} ${t("Settings")}</h2><p>${t("Edge proxy, API keys, voice, interface and data")}</p></header>
        <div class="set-tabs">
          <button class="set-tab on" data-tab="api">${ico("key")} ${t("Models & API")}</button>
          <button class="set-tab" data-tab="voice">${ico("mic")} ${t("Voice & Calls")}</button>
          <button class="set-tab" data-tab="ui">${ico("sun")} ${t("Interface")}</button>
          <button class="set-tab" data-tab="data">${ico("db")} ${t("Data")}</button>
        </div>
        <div class="set-panel" data-panel="api"></div>
        <div class="set-panel" data-panel="voice" hidden></div>
        <div class="set-panel" data-panel="ui" hidden></div>
        <div class="set-panel" data-panel="data" hidden></div>
      </div>`;
    const panels = host.querySelectorAll(".set-panel");
    host.querySelectorAll(".set-tab").forEach((tb) =>
      tb.addEventListener("click", () => {
        host.querySelectorAll(".set-tab").forEach((x) => x.classList.remove("on"));
        tb.classList.add("on");
        panels.forEach((p) => (p as HTMLElement).hidden = p.getAttribute("data-panel") !== tb.getAttribute("data-tab"));
      })
    );

    const api = host.querySelector('[data-panel="api"]')!;
    api.innerHTML = `
      <section class="set-card">
        <h3>${t("Edge proxy (Cloudflare Workers)")}</h3>
        <p class="set-hint">${t("Set the URL of your deployed worker from <code>edge/</code> — keys stay on the server. Leave empty for direct mode with the keys below.")}</p>
        <div class="edge-row">
          <input class="text-input" id="edge-url" placeholder="https://shai-edge.example.workers.dev" value="${escapeHtml(s().edgeUrl)}" />
          <button class="btn btn-ghost" id="edge-test">${ico("bolt")} ${t("Test")}</button>
        </div>
        <div class="edge-status" id="edge-status"></div>
      </section>
      <section class="set-card">
        <h3>${t("Provider API keys")}</h3>
        <p class="set-hint">${t("Stored only in your browser (IndexedDB). Without keys the offline engine runs.")}</p>
        <div class="keys-grid">${PROVIDERS.map((p) => {
          const has = !!s().keys[p.keyEnv];
          return `
          <div class="key-row">
            <label><span class="key-dot${has ? " on" : ""}"></span>${escapeHtml(p.name)}<a href="${p.keyUrl}" target="_blank" rel="noopener">${t("get key")} ${ico("external")}</a></label>
            <div class="key-input">
              <input type="password" data-key="${p.id}" placeholder="${p.keyEnv}" value="${escapeHtml(s().keys[p.keyEnv] ?? "")}" />
              <button class="icon-btn eye-btn" title="Show/hide">${ico("key")}</button>
            </div>
          </div>`;
        }).join("")}
        </div>
      </section>
      <section class="set-card">
        <h3>${t("Model catalog")}</h3>
        <p class="set-hint">${t("Aggregates <code>/v1/models</code> from all providers (via Edge or directly). Cached in IndexedDB.")}</p>
        <div class="edge-row">
          <button class="btn btn-primary" id="refresh-models">${ico("refresh")} ${t("Refresh model list")}</button>
          <span class="models-count">${t("In catalog:")} <b>${store.state.models.length}</b></span>
        </div>
      </section>`;
    api.querySelector("#edge-url")!.addEventListener("change", (e) => set({ edgeUrl: (e.target as HTMLInputElement).value.trim() }));
    api.querySelector("#edge-test")!.addEventListener("click", async () => {
      const st = api.querySelector("#edge-status")!;
      st.textContent = t("Testing…");
      st.className = "edge-status";
      const ok = await client.health();
      st.textContent = t(ok ? "Worker is up — keys live server-side, no local keys needed." : "No connection. Check the URL and the worker's CORS.");
      st.classList.add(ok ? "ok" : "bad");
    });
    api.querySelectorAll("input[data-key]").forEach((inp) => {
      inp.addEventListener("change", () => {
        const p = PROVIDERS.find((x) => x.id === inp.getAttribute("data-key"))!;
        set({ keys: { ...s().keys, [p.keyEnv]: (inp as HTMLInputElement).value.trim() } });
        (inp.closest(".key-row")!.querySelector(".key-dot") as HTMLElement).classList.toggle("on", !!(inp as HTMLInputElement).value.trim());
        toast(`${p.name}: ${t("key saved locally")}`, "ok");
      });
    });
    api.querySelectorAll(".eye-btn").forEach((b) =>
      b.addEventListener("click", () => {
        const inp = b.parentElement!.querySelector("input") as HTMLInputElement;
        inp.type = inp.type === "password" ? "text" : "password";
      })
    );
    api.querySelector("#refresh-models")!.addEventListener("click", async (e) => {
      const btn = e.currentTarget as HTMLButtonElement;
      btn.disabled = true;
      try {
        const models = await client.fetchModels(s().keys);
        store.state.models = models;
        void db.set("models", "list", { ts: Date.now(), models });
        api.querySelector(".models-count b")!.textContent = String(models.length);
        toast(`${t("Models found:")} ${models.length}`, "ok");
      } catch {
        toast(t("Couldn't refresh the catalog"), "err");
      } finally {
        btn.disabled = false;
      }
    });

    const voice = host.querySelector('[data-panel="voice"]')!;
    voice.innerHTML = `
      <section class="set-card">
        <h3>${t("Speech recognition (STT)")}</h3>
        <div class="field"><span class="field-label">${t("Dictation & call language")}</span>
          <select class="text-input" id="stt-lang">
            ${["en-US", "uk-UA", "pl-PL", "de-DE"].map((l) => `<option value="${l}"${s().sttLang === l ? " selected" : ""}>${l}</option>`).join("")}
          </select>
        </div>
      </section>
      <section class="set-card">
        <h3>${t("Speech synthesis (TTS)")}</h3>
        <div class="field"><span class="field-label">${t("Voice")}</span><select class="text-input" id="tts-voice"><option value="">${t("System default")}</option></select></div>
        <div class="field"><span class="field-label">${t("Speaking rate")}</span><div id="tts-rate"></div></div>
        <div class="field"><span class="field-label">${t("Preview")}</span><button class="btn btn-ghost" id="tts-test">${ico("volume")} ${t("Play test phrase")}</button></div>
      </section>
      <section class="set-card">
        <h3>${t("Calls")}</h3>
        <div class="field"><span class="field-label">${t("Barge-in — interrupt the AI with your voice")}</span><span id="barge"></span></div>
        <p class="set-hint">${t("While the assistant speaks, your mic amplitude is analyzed; a loud utterance stops the synthesis.")}</p>
      </section>`;
    const voiceSel = voice.querySelector("#tts-voice") as HTMLSelectElement;
    const fillVoices = () => {
      const cur = s().ttsVoice;
      voiceSel.innerHTML = `<option value="">${t("System default")}</option>` +
        window.speechSynthesis.getVoices().map((v) => `<option value="${escapeHtml(v.name)}"${v.name === cur ? " selected" : ""}>${escapeHtml(v.name)} (${v.lang})</option>`).join("");
    };
    fillVoices();
    window.speechSynthesis.onvoiceschanged = fillVoices;
    voice.querySelector("#stt-lang")!.addEventListener("change", (e) => set({ sttLang: (e.target as HTMLSelectElement).value }));
    voiceSel.addEventListener("change", () => set({ ttsVoice: voiceSel.value }));
    voice.querySelector("#tts-rate")!.appendChild(rangeEl({ min: 0.6, max: 1.6, step: 0.05, value: s().ttsRate, fmt: (v) => `${v.toFixed(2)}×`, onChange: (v) => set({ ttsRate: v }) }));
    voice.querySelector("#barge")!.appendChild(switchEl(s().bargeIn, (v) => set({ bargeIn: v })));
    voice.querySelector("#tts-test")!.addEventListener("click", () => {
      const u = new SpeechSynthesisUtterance(t("Hello! This is a speech synthesis test. Ready for a call."));
      u.lang = getLang() === "uk" ? "uk-UA" : "en-US";
      u.rate = s().ttsRate;
      const v = window.speechSynthesis.getVoices().find((x) => x.name === s().ttsVoice) ?? window.speechSynthesis.getVoices().find((x) => x.lang.startsWith(getLang() === "uk" ? "uk" : "en"));
      if (v) u.voice = v;
      window.speechSynthesis.cancel();
      window.speechSynthesis.speak(u);
    });

    const uiP = host.querySelector('[data-panel="ui"]')!;
    uiP.innerHTML = `
      <section class="set-card">
        <h3>${t("Language")}</h3>
        <div class="field"><span class="field-label">${t("Interface language")}</span>
          <div class="lang-seg">
            <button data-lang="en"${s().lang === "en" ? " class=on" : ""}>English</button>
            <button data-lang="uk"${s().lang === "uk" ? " class=on" : ""}>Українська</button>
          </div>
        </div>
      </section>
      <section class="set-card">
        <h3>${t("Appearance")}</h3>
        <div class="theme-cards">
          <button class="theme-card${s().theme === "light" ? " on" : ""}" data-th="light"><span class="tc-prev tc-light"></span>${t("Light")}</button>
          <button class="theme-card${s().theme === "dark" ? " on" : ""}" data-th="dark"><span class="tc-prev tc-dark"></span>${t("Dark")}</button>
        </div>
      </section>
      <section class="set-card">
        <h3>${t("Reading")}</h3>
        <div class="field"><span class="field-label">${t("Message text size")}</span><div id="fs"></div></div>
        <div class="field"><span class="field-label">${t("Show message timestamps")}</span><span id="sw-time"></span></div>
      </section>
      <section class="set-card">
        <h3>${t("Composer & streaming")}</h3>
        <div class="field"><span class="field-label">${t("Enter sends the message")}</span><span id="sw-enter"></span></div>
        <div class="field"><span class="field-label">${t("Gradual typing (offline engine)")}</span><span id="sw-stream"></span></div>
        <div class="field"><span class="field-label">${t("Notification sounds")}</span><span id="sw-sound"></span></div>
        <div class="field"><span class="field-label">${t("Volume")}</span><div id="vol"></div></div>
      </section>`;
    uiP.querySelectorAll("[data-lang]").forEach((b) =>
      b.addEventListener("click", () => set({ lang: b.getAttribute("data-lang") as Lang }))
    );
    uiP.querySelectorAll(".theme-card").forEach((c) =>
      c.addEventListener("click", () => {
        set({ theme: c.getAttribute("data-th") as "light" | "dark" });
        uiP.querySelectorAll(".theme-card").forEach((x) => x.classList.toggle("on", x === c));
      })
    );
    uiP.querySelector("#fs")!.appendChild(rangeEl({ min: 13, max: 19, step: 1, value: s().fontSize, fmt: (v) => `${v}px`, onChange: (v) => set({ fontSize: v }) }));
    uiP.querySelector("#sw-time")!.appendChild(switchEl(s().showTime, (v) => set({ showTime: v })));
    uiP.querySelector("#sw-enter")!.appendChild(switchEl(s().enterSend, (v) => set({ enterSend: v })));
    uiP.querySelector("#sw-stream")!.appendChild(switchEl(s().stream, (v) => set({ stream: v })));
    uiP.querySelector("#sw-sound")!.appendChild(switchEl(s().sound, (v) => set({ sound: v })));
    uiP.querySelector("#vol")!.appendChild(rangeEl({ min: 0, max: 1, step: 0.05, value: s().volume, fmt: (v) => `${Math.round(v * 100)}%`, onChange: (v) => set({ volume: v }) }));

    const dataP = host.querySelector('[data-panel="data"]')!;
    const msgsTotal = store.state.chats.reduce((n, c) => n + c.msgs.length, 0);
    const kb = Math.max(1, Math.round(JSON.stringify(store.state.chats).length / 1024));
    dataP.innerHTML = `
      <section class="set-card">
        <h3>${t("Local storage (IndexedDB)")}</h3>
        <div class="stat-grid">
          <div class="stat"><b>${store.state.chats.length}</b><span>${t("chats")}</span></div>
          <div class="stat"><b>${msgsTotal}</b><span>${t("messages")}</span></div>
          <div class="stat"><b>${kb} KB</b><span>${t("of data")}</span></div>
          <div class="stat"><b>${store.state.models.length}</b><span>${t("models in catalog")}</span></div>
        </div>
      </section>
      <section class="set-card">
        <h3>${t("Export & cleanup")}</h3>
        <div class="edge-row">
          <button class="btn btn-ghost" id="export-json">${ico("download")} ${t("Export JSON")}</button>
          <button class="btn btn-ghost danger-text" id="clear-chats">${ico("trash")} ${t("Clear all chats")}</button>
          <button class="btn btn-danger" id="wipe">${ico("alert")} ${t("Full reset")}</button>
        </div>
      </section>`;
    dataP.querySelector("#export-json")!.addEventListener("click", () => {
      const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), settings: s(), chats: store.state.chats }, null, 2)], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "shai-export.json";
      a.click();
      URL.revokeObjectURL(url);
      toast(t("Exported"), "ok");
    });
    dataP.querySelector("#clear-chats")!.addEventListener("click", async () => {
      const ok = await confirmDialog({ title: t("Clear chats?"), text: t("All chat history will be removed from IndexedDB. Settings stay."), okText: t("Clear"), danger: true });
      if (!ok) return;
      store.state.chats = [makeChat()];
      persist();
      router.navigate(`#/c/${store.state.chats[0].id}`);
      renderSettings();
      toast(t("History cleared"), "ok");
    });
    dataP.querySelector("#wipe")!.addEventListener("click", async () => {
      const ok = await confirmDialog({ title: t("Full reset?"), text: t("Everything will be deleted: chats, settings, keys and the model cache. This can't be undone."), okText: t("Reset everything"), danger: true });
      if (!ok) return;
      await db.clear("chats");
      await db.clear("settings");
      await db.clear("models");
      await db.clear("misc");
      location.hash = "";
      location.reload();
    });
  }

  chatListEl.addEventListener("click", (e) => {
    const btn = (e.target as HTMLElement).closest("[data-ciact]") as HTMLElement | null;
    if (!btn) return;
    e.preventDefault();
    const id = btn.closest(".chat-item")?.getAttribute("data-id") ?? "";
    const chat = store.state.chats.find((c) => c.id === id);
    if (!chat) return;
    if (btn.getAttribute("data-ciact") === "rename") {
      void promptDialog({ title: "Rename conversation", label: "Title", value: chat.title }).then((v) => {
        if (v) {
          chat.title = v;
          chat.updatedAt = Date.now();
          persist();
          renderChatList(searchInput.value);
        }
      });
    } else {
      void confirmDialog({ title: t("Delete conversation?"), text: t("The conversation and all its messages will be removed from IndexedDB."), okText: t("Delete"), danger: true }).then((ok) => {
        if (!ok) return;
        store.state.chats = store.state.chats.filter((c) => c.id !== id);
        if (!store.state.chats.length) store.state.chats = [makeChat()];
        persist();
        if (store.state.activeId === id) router.navigate(`#/c/${store.state.chats[0].id}`);
        else renderChatList(searchInput.value);
      });
    }
  });

  searchInput.addEventListener("input", () => renderChatList(searchInput.value));
  root.querySelector(".btn-new")!.addEventListener("click", () => {
    const c = makeChat();
    store.state.chats = [c, ...store.state.chats];
    persist();
    router.navigate(`#/c/${c.id}`);
  });
  root.querySelector(".sidebar-scrim")!.addEventListener("click", () => { store.state.sidebarOpen = false; });
  root.querySelector(".art-close")!.addEventListener("click", () => { store.state.artOpen = false; });

  window.addEventListener("keydown", (e) => {
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "b") {
      e.preventDefault();
      if (innerWidth <= 920) store.state.sidebarOpen = !store.state.sidebarOpen;
      else store.state.sideCollapsed = !store.state.sideCollapsed;
    }
  });

  unsubs.push(store.watch(["chats", "activeId", "view"], () => renderChatList(searchInput.value)));
  let prevLang = s().lang;
  unsubs.push(store.watch(["settings"], () => {
    void db.set("settings", "app", store.state.settings);
    applyTheme();
    if (s().lang !== prevLang) {
      prevLang = s().lang;
      setLang(s().lang);
      updateI18nAll();
    }
  }));
  unsubs.push(store.watch(["sidebarOpen"], () => shell.classList.toggle("side-open", store.state.sidebarOpen)));
  unsubs.push(store.watch(["sideCollapsed"], () => shell.classList.toggle("side-collapsed", store.state.sideCollapsed)));
  unsubs.push(store.watch(["artOpen"], () => shell.classList.toggle("art-open", store.state.artOpen)));

  function applyTheme(): void {
    document.documentElement.dataset.theme = s().theme;
    document.documentElement.style.setProperty("--fs", `${s().fontSize}px`);
    const meta = document.querySelector('meta[name="theme-color"]');
    if (meta) meta.setAttribute("content", s().theme === "dark" ? "#141416" : "#f4f4f6");
  }

  function updateI18nAll(): void {
    document.documentElement.lang = getLang();
    applyI18n(root);
    engine.applyLang();
    renderChatList(searchInput.value);
    if (store.state.view === "settings") renderSettings();
    if (store.state.view === "about") renderAbout();
    renderArtifacts();
  }

  applyTheme();

  router
    .add("#/c/:id", (p) => {
      const chat = store.state.chats.find((c) => c.id === p.id);
      if (!chat) { router.navigate(`#/c/${store.state.chats[0]?.id ?? ""}`); return; }
      store.state.activeId = chat.id;
      showView("chat");
      engine.renderChat();
      refreshArtifacts();
      renderChatList(searchInput.value);
    })
    .add("#/settings", () => showView("settings"))
    .add("#/about", () => showView("about"))
    .setFallback(() => router.navigate(`#/c/${store.state.activeId || store.state.chats[0]?.id}`));

  renderChatList();
  router.start();

  if (settings.edgeUrl || Object.values(settings.keys).some(Boolean)) {
    client.fetchModels(s().keys)
      .then((models) => {
        if (models.length > 1) {
          store.state.models = models;
          void db.set("models", "list", { ts: Date.now(), models });
        }
      })
      .catch(() => {});
  }

  return () => {
    callMgr?.end(false);
    router.destroy();
    unsubs.forEach((u) => u());
    root.innerHTML = "";
  };
}
